//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EXACTUSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EXACTUSEntities object using the connection string found in the 'EXACTUSEntities' section of the application configuration file.
        /// </summary>
        public EXACTUSEntities() : base("name=EXACTUSEntities", "EXACTUSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EXACTUSEntities object.
        /// </summary>
        public EXACTUSEntities(string connectionString) : base(connectionString, "EXACTUSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EXACTUSEntities object.
        /// </summary>
        public EXACTUSEntities(EntityConnection connection) : base(connection, "EXACTUSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ACCION> ACCIONs
        {
            get
            {
                if ((_ACCIONs == null))
                {
                    _ACCIONs = base.CreateObjectSet<ACCION>("ACCIONs");
                }
                return _ACCIONs;
            }
        }
        private ObjectSet<ACCION> _ACCIONs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ACCION_VERSION> ACCION_VERSION
        {
            get
            {
                if ((_ACCION_VERSION == null))
                {
                    _ACCION_VERSION = base.CreateObjectSet<ACCION_VERSION>("ACCION_VERSION");
                }
                return _ACCION_VERSION;
            }
        }
        private ObjectSet<ACCION_VERSION> _ACCION_VERSION;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AccountAuthorization> AccountAuthorizations
        {
            get
            {
                if ((_AccountAuthorizations == null))
                {
                    _AccountAuthorizations = base.CreateObjectSet<AccountAuthorization>("AccountAuthorizations");
                }
                return _AccountAuthorizations;
            }
        }
        private ObjectSet<AccountAuthorization> _AccountAuthorizations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ActiveBGTask> ActiveBGTasks
        {
            get
            {
                if ((_ActiveBGTasks == null))
                {
                    _ActiveBGTasks = base.CreateObjectSet<ActiveBGTask>("ActiveBGTasks");
                }
                return _ActiveBGTasks;
            }
        }
        private ObjectSet<ActiveBGTask> _ActiveBGTasks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ADMIN_CONCEPTO> ADMIN_CONCEPTO
        {
            get
            {
                if ((_ADMIN_CONCEPTO == null))
                {
                    _ADMIN_CONCEPTO = base.CreateObjectSet<ADMIN_CONCEPTO>("ADMIN_CONCEPTO");
                }
                return _ADMIN_CONCEPTO;
            }
        }
        private ObjectSet<ADMIN_CONCEPTO> _ADMIN_CONCEPTO;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ACCIONs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToACCIONs(ACCION aCCION)
        {
            base.AddObject("ACCIONs", aCCION);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ACCION_VERSION EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToACCION_VERSION(ACCION_VERSION aCCION_VERSION)
        {
            base.AddObject("ACCION_VERSION", aCCION_VERSION);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AccountAuthorizations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccountAuthorizations(AccountAuthorization accountAuthorization)
        {
            base.AddObject("AccountAuthorizations", accountAuthorization);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ActiveBGTasks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActiveBGTasks(ActiveBGTask activeBGTask)
        {
            base.AddObject("ActiveBGTasks", activeBGTask);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ADMIN_CONCEPTO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToADMIN_CONCEPTO(ADMIN_CONCEPTO aDMIN_CONCEPTO)
        {
            base.AddObject("ADMIN_CONCEPTO", aDMIN_CONCEPTO);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EXACTUSModel", Name="ACCION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ACCION : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ACCION object.
        /// </summary>
        /// <param name="aCCION1">Initial value of the ACCION1 property.</param>
        /// <param name="nOMBREACCION">Initial value of the NOMBREACCION property.</param>
        /// <param name="nOMBRECONSTANTE">Initial value of the NOMBRECONSTANTE property.</param>
        /// <param name="eSMODULO">Initial value of the ESMODULO property.</param>
        /// <param name="eSESTANDAR">Initial value of the ESESTANDAR property.</param>
        /// <param name="noteExistsFlag">Initial value of the NoteExistsFlag property.</param>
        /// <param name="recordDate">Initial value of the RecordDate property.</param>
        /// <param name="rowPointer">Initial value of the RowPointer property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="updatedBy">Initial value of the UpdatedBy property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="tIPO">Initial value of the TIPO property.</param>
        /// <param name="sUBTIPO">Initial value of the SUBTIPO property.</param>
        public static ACCION CreateACCION(global::System.Int32 aCCION1, global::System.String nOMBREACCION, global::System.String nOMBRECONSTANTE, global::System.String eSMODULO, global::System.String eSESTANDAR, global::System.Byte noteExistsFlag, global::System.DateTime recordDate, global::System.Guid rowPointer, global::System.String createdBy, global::System.String updatedBy, global::System.DateTime createDate, global::System.String tIPO, global::System.String sUBTIPO)
        {
            ACCION aCCION = new ACCION();
            aCCION.ACCION1 = aCCION1;
            aCCION.NOMBREACCION = nOMBREACCION;
            aCCION.NOMBRECONSTANTE = nOMBRECONSTANTE;
            aCCION.ESMODULO = eSMODULO;
            aCCION.ESESTANDAR = eSESTANDAR;
            aCCION.NoteExistsFlag = noteExistsFlag;
            aCCION.RecordDate = recordDate;
            aCCION.RowPointer = rowPointer;
            aCCION.CreatedBy = createdBy;
            aCCION.UpdatedBy = updatedBy;
            aCCION.CreateDate = createDate;
            aCCION.TIPO = tIPO;
            aCCION.SUBTIPO = sUBTIPO;
            return aCCION;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ACCION1
        {
            get
            {
                return _ACCION1;
            }
            set
            {
                if (_ACCION1 != value)
                {
                    OnACCION1Changing(value);
                    ReportPropertyChanging("ACCION1");
                    _ACCION1 = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ACCION1");
                    OnACCION1Changed();
                }
            }
        }
        private global::System.Int32 _ACCION1;
        partial void OnACCION1Changing(global::System.Int32 value);
        partial void OnACCION1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBREACCION
        {
            get
            {
                return _NOMBREACCION;
            }
            set
            {
                OnNOMBREACCIONChanging(value);
                ReportPropertyChanging("NOMBREACCION");
                _NOMBREACCION = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBREACCION");
                OnNOMBREACCIONChanged();
            }
        }
        private global::System.String _NOMBREACCION;
        partial void OnNOMBREACCIONChanging(global::System.String value);
        partial void OnNOMBREACCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPCION
        {
            get
            {
                return _DESCRIPCION;
            }
            set
            {
                OnDESCRIPCIONChanging(value);
                ReportPropertyChanging("DESCRIPCION");
                _DESCRIPCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPCION");
                OnDESCRIPCIONChanged();
            }
        }
        private global::System.String _DESCRIPCION;
        partial void OnDESCRIPCIONChanging(global::System.String value);
        partial void OnDESCRIPCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NOMBRECONSTANTE
        {
            get
            {
                return _NOMBRECONSTANTE;
            }
            set
            {
                OnNOMBRECONSTANTEChanging(value);
                ReportPropertyChanging("NOMBRECONSTANTE");
                _NOMBRECONSTANTE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NOMBRECONSTANTE");
                OnNOMBRECONSTANTEChanged();
            }
        }
        private global::System.String _NOMBRECONSTANTE;
        partial void OnNOMBRECONSTANTEChanging(global::System.String value);
        partial void OnNOMBRECONSTANTEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESMODULO
        {
            get
            {
                return _ESMODULO;
            }
            set
            {
                OnESMODULOChanging(value);
                ReportPropertyChanging("ESMODULO");
                _ESMODULO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ESMODULO");
                OnESMODULOChanged();
            }
        }
        private global::System.String _ESMODULO;
        partial void OnESMODULOChanging(global::System.String value);
        partial void OnESMODULOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ESESTANDAR
        {
            get
            {
                return _ESESTANDAR;
            }
            set
            {
                OnESESTANDARChanging(value);
                ReportPropertyChanging("ESESTANDAR");
                _ESESTANDAR = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ESESTANDAR");
                OnESESTANDARChanged();
            }
        }
        private global::System.String _ESESTANDAR;
        partial void OnESESTANDARChanging(global::System.String value);
        partial void OnESESTANDARChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte NoteExistsFlag
        {
            get
            {
                return _NoteExistsFlag;
            }
            set
            {
                OnNoteExistsFlagChanging(value);
                ReportPropertyChanging("NoteExistsFlag");
                _NoteExistsFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoteExistsFlag");
                OnNoteExistsFlagChanged();
            }
        }
        private global::System.Byte _NoteExistsFlag;
        partial void OnNoteExistsFlagChanging(global::System.Byte value);
        partial void OnNoteExistsFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RecordDate
        {
            get
            {
                return _RecordDate;
            }
            set
            {
                OnRecordDateChanging(value);
                ReportPropertyChanging("RecordDate");
                _RecordDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecordDate");
                OnRecordDateChanged();
            }
        }
        private global::System.DateTime _RecordDate;
        partial void OnRecordDateChanging(global::System.DateTime value);
        partial void OnRecordDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RowPointer
        {
            get
            {
                return _RowPointer;
            }
            set
            {
                OnRowPointerChanging(value);
                ReportPropertyChanging("RowPointer");
                _RowPointer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RowPointer");
                OnRowPointerChanged();
            }
        }
        private global::System.Guid _RowPointer;
        partial void OnRowPointerChanging(global::System.Guid value);
        partial void OnRowPointerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TIPO
        {
            get
            {
                return _TIPO;
            }
            set
            {
                OnTIPOChanging(value);
                ReportPropertyChanging("TIPO");
                _TIPO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TIPO");
                OnTIPOChanged();
            }
        }
        private global::System.String _TIPO;
        partial void OnTIPOChanging(global::System.String value);
        partial void OnTIPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SUBTIPO
        {
            get
            {
                return _SUBTIPO;
            }
            set
            {
                OnSUBTIPOChanging(value);
                ReportPropertyChanging("SUBTIPO");
                _SUBTIPO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SUBTIPO");
                OnSUBTIPOChanged();
            }
        }
        private global::System.String _SUBTIPO;
        partial void OnSUBTIPOChanging(global::System.String value);
        partial void OnSUBTIPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TABLA
        {
            get
            {
                return _TABLA;
            }
            set
            {
                OnTABLAChanging(value);
                ReportPropertyChanging("TABLA");
                _TABLA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TABLA");
                OnTABLAChanged();
            }
        }
        private global::System.String _TABLA;
        partial void OnTABLAChanging(global::System.String value);
        partial void OnTABLAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String INVOCACION
        {
            get
            {
                return _INVOCACION;
            }
            set
            {
                OnINVOCACIONChanging(value);
                ReportPropertyChanging("INVOCACION");
                _INVOCACION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("INVOCACION");
                OnINVOCACIONChanged();
            }
        }
        private global::System.String _INVOCACION;
        partial void OnINVOCACIONChanging(global::System.String value);
        partial void OnINVOCACIONChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EXACTUSModel", Name="ACCION_VERSION")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ACCION_VERSION : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ACCION_VERSION object.
        /// </summary>
        /// <param name="aCCION">Initial value of the ACCION property.</param>
        /// <param name="uSUARIO">Initial value of the USUARIO property.</param>
        /// <param name="fCH_HORA_VERSION">Initial value of the FCH_HORA_VERSION property.</param>
        /// <param name="noteExistsFlag">Initial value of the NoteExistsFlag property.</param>
        /// <param name="recordDate">Initial value of the RecordDate property.</param>
        /// <param name="rowPointer">Initial value of the RowPointer property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="updatedBy">Initial value of the UpdatedBy property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="uLT_VERSIONERP">Initial value of the ULT_VERSIONERP property.</param>
        public static ACCION_VERSION CreateACCION_VERSION(global::System.Int32 aCCION, global::System.String uSUARIO, global::System.DateTime fCH_HORA_VERSION, global::System.Byte noteExistsFlag, global::System.DateTime recordDate, global::System.Guid rowPointer, global::System.String createdBy, global::System.String updatedBy, global::System.DateTime createDate, global::System.String uLT_VERSIONERP)
        {
            ACCION_VERSION aCCION_VERSION = new ACCION_VERSION();
            aCCION_VERSION.ACCION = aCCION;
            aCCION_VERSION.USUARIO = uSUARIO;
            aCCION_VERSION.FCH_HORA_VERSION = fCH_HORA_VERSION;
            aCCION_VERSION.NoteExistsFlag = noteExistsFlag;
            aCCION_VERSION.RecordDate = recordDate;
            aCCION_VERSION.RowPointer = rowPointer;
            aCCION_VERSION.CreatedBy = createdBy;
            aCCION_VERSION.UpdatedBy = updatedBy;
            aCCION_VERSION.CreateDate = createDate;
            aCCION_VERSION.ULT_VERSIONERP = uLT_VERSIONERP;
            return aCCION_VERSION;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ACCION
        {
            get
            {
                return _ACCION;
            }
            set
            {
                if (_ACCION != value)
                {
                    OnACCIONChanging(value);
                    ReportPropertyChanging("ACCION");
                    _ACCION = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ACCION");
                    OnACCIONChanged();
                }
            }
        }
        private global::System.Int32 _ACCION;
        partial void OnACCIONChanging(global::System.Int32 value);
        partial void OnACCIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ULT_VERSION
        {
            get
            {
                return _ULT_VERSION;
            }
            set
            {
                OnULT_VERSIONChanging(value);
                ReportPropertyChanging("ULT_VERSION");
                _ULT_VERSION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ULT_VERSION");
                OnULT_VERSIONChanged();
            }
        }
        private global::System.String _ULT_VERSION;
        partial void OnULT_VERSIONChanging(global::System.String value);
        partial void OnULT_VERSIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String USUARIO
        {
            get
            {
                return _USUARIO;
            }
            set
            {
                if (_USUARIO != value)
                {
                    OnUSUARIOChanging(value);
                    ReportPropertyChanging("USUARIO");
                    _USUARIO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("USUARIO");
                    OnUSUARIOChanged();
                }
            }
        }
        private global::System.String _USUARIO;
        partial void OnUSUARIOChanging(global::System.String value);
        partial void OnUSUARIOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FCH_HORA_VERSION
        {
            get
            {
                return _FCH_HORA_VERSION;
            }
            set
            {
                if (_FCH_HORA_VERSION != value)
                {
                    OnFCH_HORA_VERSIONChanging(value);
                    ReportPropertyChanging("FCH_HORA_VERSION");
                    _FCH_HORA_VERSION = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FCH_HORA_VERSION");
                    OnFCH_HORA_VERSIONChanged();
                }
            }
        }
        private global::System.DateTime _FCH_HORA_VERSION;
        partial void OnFCH_HORA_VERSIONChanging(global::System.DateTime value);
        partial void OnFCH_HORA_VERSIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte NoteExistsFlag
        {
            get
            {
                return _NoteExistsFlag;
            }
            set
            {
                if (_NoteExistsFlag != value)
                {
                    OnNoteExistsFlagChanging(value);
                    ReportPropertyChanging("NoteExistsFlag");
                    _NoteExistsFlag = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NoteExistsFlag");
                    OnNoteExistsFlagChanged();
                }
            }
        }
        private global::System.Byte _NoteExistsFlag;
        partial void OnNoteExistsFlagChanging(global::System.Byte value);
        partial void OnNoteExistsFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RecordDate
        {
            get
            {
                return _RecordDate;
            }
            set
            {
                if (_RecordDate != value)
                {
                    OnRecordDateChanging(value);
                    ReportPropertyChanging("RecordDate");
                    _RecordDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecordDate");
                    OnRecordDateChanged();
                }
            }
        }
        private global::System.DateTime _RecordDate;
        partial void OnRecordDateChanging(global::System.DateTime value);
        partial void OnRecordDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RowPointer
        {
            get
            {
                return _RowPointer;
            }
            set
            {
                if (_RowPointer != value)
                {
                    OnRowPointerChanging(value);
                    ReportPropertyChanging("RowPointer");
                    _RowPointer = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RowPointer");
                    OnRowPointerChanged();
                }
            }
        }
        private global::System.Guid _RowPointer;
        partial void OnRowPointerChanging(global::System.Guid value);
        partial void OnRowPointerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                if (_CreatedBy != value)
                {
                    OnCreatedByChanging(value);
                    ReportPropertyChanging("CreatedBy");
                    _CreatedBy = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CreatedBy");
                    OnCreatedByChanged();
                }
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                if (_UpdatedBy != value)
                {
                    OnUpdatedByChanging(value);
                    ReportPropertyChanging("UpdatedBy");
                    _UpdatedBy = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UpdatedBy");
                    OnUpdatedByChanged();
                }
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                if (_CreateDate != value)
                {
                    OnCreateDateChanging(value);
                    ReportPropertyChanging("CreateDate");
                    _CreateDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CreateDate");
                    OnCreateDateChanged();
                }
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ULT_VERSIONERP
        {
            get
            {
                return _ULT_VERSIONERP;
            }
            set
            {
                if (_ULT_VERSIONERP != value)
                {
                    OnULT_VERSIONERPChanging(value);
                    ReportPropertyChanging("ULT_VERSIONERP");
                    _ULT_VERSIONERP = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ULT_VERSIONERP");
                    OnULT_VERSIONERPChanged();
                }
            }
        }
        private global::System.String _ULT_VERSIONERP;
        partial void OnULT_VERSIONERPChanging(global::System.String value);
        partial void OnULT_VERSIONERPChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EXACTUSModel", Name="AccountAuthorization")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AccountAuthorization : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AccountAuthorization object.
        /// </summary>
        /// <param name="objectName1">Initial value of the ObjectName1 property.</param>
        /// <param name="objectType">Initial value of the ObjectType property.</param>
        /// <param name="objectName2">Initial value of the ObjectName2 property.</param>
        /// <param name="userFlag">Initial value of the UserFlag property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="noteExistsFlag">Initial value of the NoteExistsFlag property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="updatedBy">Initial value of the UpdatedBy property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="recordDate">Initial value of the RecordDate property.</param>
        /// <param name="rowPointer">Initial value of the RowPointer property.</param>
        public static AccountAuthorization CreateAccountAuthorization(global::System.String objectName1, global::System.Int16 objectType, global::System.String objectName2, global::System.Int16 userFlag, global::System.Decimal id, global::System.Byte noteExistsFlag, global::System.String createdBy, global::System.String updatedBy, global::System.DateTime createDate, global::System.DateTime recordDate, global::System.Guid rowPointer)
        {
            AccountAuthorization accountAuthorization = new AccountAuthorization();
            accountAuthorization.ObjectName1 = objectName1;
            accountAuthorization.ObjectType = objectType;
            accountAuthorization.ObjectName2 = objectName2;
            accountAuthorization.UserFlag = userFlag;
            accountAuthorization.Id = id;
            accountAuthorization.NoteExistsFlag = noteExistsFlag;
            accountAuthorization.CreatedBy = createdBy;
            accountAuthorization.UpdatedBy = updatedBy;
            accountAuthorization.CreateDate = createDate;
            accountAuthorization.RecordDate = recordDate;
            accountAuthorization.RowPointer = rowPointer;
            return accountAuthorization;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ObjectName1
        {
            get
            {
                return _ObjectName1;
            }
            set
            {
                if (_ObjectName1 != value)
                {
                    OnObjectName1Changing(value);
                    ReportPropertyChanging("ObjectName1");
                    _ObjectName1 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ObjectName1");
                    OnObjectName1Changed();
                }
            }
        }
        private global::System.String _ObjectName1;
        partial void OnObjectName1Changing(global::System.String value);
        partial void OnObjectName1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ObjectType
        {
            get
            {
                return _ObjectType;
            }
            set
            {
                if (_ObjectType != value)
                {
                    OnObjectTypeChanging(value);
                    ReportPropertyChanging("ObjectType");
                    _ObjectType = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ObjectType");
                    OnObjectTypeChanged();
                }
            }
        }
        private global::System.Int16 _ObjectType;
        partial void OnObjectTypeChanging(global::System.Int16 value);
        partial void OnObjectTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ObjectName2
        {
            get
            {
                return _ObjectName2;
            }
            set
            {
                if (_ObjectName2 != value)
                {
                    OnObjectName2Changing(value);
                    ReportPropertyChanging("ObjectName2");
                    _ObjectName2 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ObjectName2");
                    OnObjectName2Changed();
                }
            }
        }
        private global::System.String _ObjectName2;
        partial void OnObjectName2Changing(global::System.String value);
        partial void OnObjectName2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 UserFlag
        {
            get
            {
                return _UserFlag;
            }
            set
            {
                if (_UserFlag != value)
                {
                    OnUserFlagChanging(value);
                    ReportPropertyChanging("UserFlag");
                    _UserFlag = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserFlag");
                    OnUserFlagChanged();
                }
            }
        }
        private global::System.Int16 _UserFlag;
        partial void OnUserFlagChanging(global::System.Int16 value);
        partial void OnUserFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Decimal _Id;
        partial void OnIdChanging(global::System.Decimal value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ReadPrivilege
        {
            get
            {
                return _ReadPrivilege;
            }
            set
            {
                OnReadPrivilegeChanging(value);
                ReportPropertyChanging("ReadPrivilege");
                _ReadPrivilege = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReadPrivilege");
                OnReadPrivilegeChanged();
            }
        }
        private Nullable<global::System.Int16> _ReadPrivilege;
        partial void OnReadPrivilegeChanging(Nullable<global::System.Int16> value);
        partial void OnReadPrivilegeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> UpdatePrivilege
        {
            get
            {
                return _UpdatePrivilege;
            }
            set
            {
                OnUpdatePrivilegeChanging(value);
                ReportPropertyChanging("UpdatePrivilege");
                _UpdatePrivilege = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatePrivilege");
                OnUpdatePrivilegeChanged();
            }
        }
        private Nullable<global::System.Int16> _UpdatePrivilege;
        partial void OnUpdatePrivilegeChanging(Nullable<global::System.Int16> value);
        partial void OnUpdatePrivilegeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> BulkUpdatePrivilege
        {
            get
            {
                return _BulkUpdatePrivilege;
            }
            set
            {
                OnBulkUpdatePrivilegeChanging(value);
                ReportPropertyChanging("BulkUpdatePrivilege");
                _BulkUpdatePrivilege = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BulkUpdatePrivilege");
                OnBulkUpdatePrivilegeChanged();
            }
        }
        private Nullable<global::System.Int16> _BulkUpdatePrivilege;
        partial void OnBulkUpdatePrivilegeChanging(Nullable<global::System.Int16> value);
        partial void OnBulkUpdatePrivilegeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> InsertPrivilege
        {
            get
            {
                return _InsertPrivilege;
            }
            set
            {
                OnInsertPrivilegeChanging(value);
                ReportPropertyChanging("InsertPrivilege");
                _InsertPrivilege = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InsertPrivilege");
                OnInsertPrivilegeChanged();
            }
        }
        private Nullable<global::System.Int16> _InsertPrivilege;
        partial void OnInsertPrivilegeChanging(Nullable<global::System.Int16> value);
        partial void OnInsertPrivilegeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> DeletePrivilege
        {
            get
            {
                return _DeletePrivilege;
            }
            set
            {
                OnDeletePrivilegeChanging(value);
                ReportPropertyChanging("DeletePrivilege");
                _DeletePrivilege = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletePrivilege");
                OnDeletePrivilegeChanged();
            }
        }
        private Nullable<global::System.Int16> _DeletePrivilege;
        partial void OnDeletePrivilegeChanging(Nullable<global::System.Int16> value);
        partial void OnDeletePrivilegeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> EditPrivilege
        {
            get
            {
                return _EditPrivilege;
            }
            set
            {
                OnEditPrivilegeChanging(value);
                ReportPropertyChanging("EditPrivilege");
                _EditPrivilege = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EditPrivilege");
                OnEditPrivilegeChanged();
            }
        }
        private Nullable<global::System.Int16> _EditPrivilege;
        partial void OnEditPrivilegeChanging(Nullable<global::System.Int16> value);
        partial void OnEditPrivilegeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ExecutePrivilege
        {
            get
            {
                return _ExecutePrivilege;
            }
            set
            {
                OnExecutePrivilegeChanging(value);
                ReportPropertyChanging("ExecutePrivilege");
                _ExecutePrivilege = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExecutePrivilege");
                OnExecutePrivilegeChanged();
            }
        }
        private Nullable<global::System.Int16> _ExecutePrivilege;
        partial void OnExecutePrivilegeChanging(Nullable<global::System.Int16> value);
        partial void OnExecutePrivilegeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte NoteExistsFlag
        {
            get
            {
                return _NoteExistsFlag;
            }
            set
            {
                OnNoteExistsFlagChanging(value);
                ReportPropertyChanging("NoteExistsFlag");
                _NoteExistsFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoteExistsFlag");
                OnNoteExistsFlagChanged();
            }
        }
        private global::System.Byte _NoteExistsFlag;
        partial void OnNoteExistsFlagChanging(global::System.Byte value);
        partial void OnNoteExistsFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RecordDate
        {
            get
            {
                return _RecordDate;
            }
            set
            {
                OnRecordDateChanging(value);
                ReportPropertyChanging("RecordDate");
                _RecordDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecordDate");
                OnRecordDateChanged();
            }
        }
        private global::System.DateTime _RecordDate;
        partial void OnRecordDateChanging(global::System.DateTime value);
        partial void OnRecordDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RowPointer
        {
            get
            {
                return _RowPointer;
            }
            set
            {
                OnRowPointerChanging(value);
                ReportPropertyChanging("RowPointer");
                _RowPointer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RowPointer");
                OnRowPointerChanged();
            }
        }
        private global::System.Guid _RowPointer;
        partial void OnRowPointerChanging(global::System.Guid value);
        partial void OnRowPointerChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EXACTUSModel", Name="ActiveBGTask")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ActiveBGTask : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ActiveBGTask object.
        /// </summary>
        /// <param name="taskNumber">Initial value of the TaskNumber property.</param>
        /// <param name="taskName">Initial value of the TaskName property.</param>
        /// <param name="taskTypeCode">Initial value of the TaskTypeCode property.</param>
        /// <param name="taskExecutable">Initial value of the TaskExecutable property.</param>
        /// <param name="requestingUser">Initial value of the RequestingUser property.</param>
        /// <param name="taskStatusCode">Initial value of the TaskStatusCode property.</param>
        /// <param name="taskDescription">Initial value of the TaskDescription property.</param>
        /// <param name="taskParms1">Initial value of the TaskParms1 property.</param>
        /// <param name="taskParms2">Initial value of the TaskParms2 property.</param>
        /// <param name="padding1">Initial value of the Padding1 property.</param>
        /// <param name="noteExistsFlag">Initial value of the NoteExistsFlag property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="updatedBy">Initial value of the UpdatedBy property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        /// <param name="recordDate">Initial value of the RecordDate property.</param>
        /// <param name="rowPointer">Initial value of the RowPointer property.</param>
        public static ActiveBGTask CreateActiveBGTask(global::System.Decimal taskNumber, global::System.String taskName, global::System.String taskTypeCode, global::System.String taskExecutable, global::System.String requestingUser, global::System.String taskStatusCode, global::System.String taskDescription, global::System.String taskParms1, global::System.String taskParms2, global::System.String padding1, global::System.Byte noteExistsFlag, global::System.String createdBy, global::System.String updatedBy, global::System.DateTime createDate, global::System.DateTime recordDate, global::System.Guid rowPointer)
        {
            ActiveBGTask activeBGTask = new ActiveBGTask();
            activeBGTask.TaskNumber = taskNumber;
            activeBGTask.TaskName = taskName;
            activeBGTask.TaskTypeCode = taskTypeCode;
            activeBGTask.TaskExecutable = taskExecutable;
            activeBGTask.RequestingUser = requestingUser;
            activeBGTask.TaskStatusCode = taskStatusCode;
            activeBGTask.TaskDescription = taskDescription;
            activeBGTask.TaskParms1 = taskParms1;
            activeBGTask.TaskParms2 = taskParms2;
            activeBGTask.Padding1 = padding1;
            activeBGTask.NoteExistsFlag = noteExistsFlag;
            activeBGTask.CreatedBy = createdBy;
            activeBGTask.UpdatedBy = updatedBy;
            activeBGTask.CreateDate = createDate;
            activeBGTask.RecordDate = recordDate;
            activeBGTask.RowPointer = rowPointer;
            return activeBGTask;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TaskNumber
        {
            get
            {
                return _TaskNumber;
            }
            set
            {
                if (_TaskNumber != value)
                {
                    OnTaskNumberChanging(value);
                    ReportPropertyChanging("TaskNumber");
                    _TaskNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaskNumber");
                    OnTaskNumberChanged();
                }
            }
        }
        private global::System.Decimal _TaskNumber;
        partial void OnTaskNumberChanging(global::System.Decimal value);
        partial void OnTaskNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TaskName
        {
            get
            {
                return _TaskName;
            }
            set
            {
                OnTaskNameChanging(value);
                ReportPropertyChanging("TaskName");
                _TaskName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TaskName");
                OnTaskNameChanged();
            }
        }
        private global::System.String _TaskName;
        partial void OnTaskNameChanging(global::System.String value);
        partial void OnTaskNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TaskTypeCode
        {
            get
            {
                return _TaskTypeCode;
            }
            set
            {
                OnTaskTypeCodeChanging(value);
                ReportPropertyChanging("TaskTypeCode");
                _TaskTypeCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TaskTypeCode");
                OnTaskTypeCodeChanged();
            }
        }
        private global::System.String _TaskTypeCode;
        partial void OnTaskTypeCodeChanging(global::System.String value);
        partial void OnTaskTypeCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TaskExecutable
        {
            get
            {
                return _TaskExecutable;
            }
            set
            {
                OnTaskExecutableChanging(value);
                ReportPropertyChanging("TaskExecutable");
                _TaskExecutable = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TaskExecutable");
                OnTaskExecutableChanged();
            }
        }
        private global::System.String _TaskExecutable;
        partial void OnTaskExecutableChanging(global::System.String value);
        partial void OnTaskExecutableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RequestingUser
        {
            get
            {
                return _RequestingUser;
            }
            set
            {
                OnRequestingUserChanging(value);
                ReportPropertyChanging("RequestingUser");
                _RequestingUser = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RequestingUser");
                OnRequestingUserChanged();
            }
        }
        private global::System.String _RequestingUser;
        partial void OnRequestingUserChanging(global::System.String value);
        partial void OnRequestingUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TaskStatusCode
        {
            get
            {
                return _TaskStatusCode;
            }
            set
            {
                OnTaskStatusCodeChanging(value);
                ReportPropertyChanging("TaskStatusCode");
                _TaskStatusCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TaskStatusCode");
                OnTaskStatusCodeChanged();
            }
        }
        private global::System.String _TaskStatusCode;
        partial void OnTaskStatusCodeChanging(global::System.String value);
        partial void OnTaskStatusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TaskDescription
        {
            get
            {
                return _TaskDescription;
            }
            set
            {
                OnTaskDescriptionChanging(value);
                ReportPropertyChanging("TaskDescription");
                _TaskDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TaskDescription");
                OnTaskDescriptionChanged();
            }
        }
        private global::System.String _TaskDescription;
        partial void OnTaskDescriptionChanging(global::System.String value);
        partial void OnTaskDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TaskParms1
        {
            get
            {
                return _TaskParms1;
            }
            set
            {
                OnTaskParms1Changing(value);
                ReportPropertyChanging("TaskParms1");
                _TaskParms1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TaskParms1");
                OnTaskParms1Changed();
            }
        }
        private global::System.String _TaskParms1;
        partial void OnTaskParms1Changing(global::System.String value);
        partial void OnTaskParms1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TaskParms2
        {
            get
            {
                return _TaskParms2;
            }
            set
            {
                OnTaskParms2Changing(value);
                ReportPropertyChanging("TaskParms2");
                _TaskParms2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TaskParms2");
                OnTaskParms2Changed();
            }
        }
        private global::System.String _TaskParms2;
        partial void OnTaskParms2Changing(global::System.String value);
        partial void OnTaskParms2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Padding1
        {
            get
            {
                return _Padding1;
            }
            set
            {
                OnPadding1Changing(value);
                ReportPropertyChanging("Padding1");
                _Padding1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Padding1");
                OnPadding1Changed();
            }
        }
        private global::System.String _Padding1;
        partial void OnPadding1Changing(global::System.String value);
        partial void OnPadding1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte NoteExistsFlag
        {
            get
            {
                return _NoteExistsFlag;
            }
            set
            {
                OnNoteExistsFlagChanging(value);
                ReportPropertyChanging("NoteExistsFlag");
                _NoteExistsFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoteExistsFlag");
                OnNoteExistsFlagChanged();
            }
        }
        private global::System.Byte _NoteExistsFlag;
        partial void OnNoteExistsFlagChanging(global::System.Byte value);
        partial void OnNoteExistsFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RecordDate
        {
            get
            {
                return _RecordDate;
            }
            set
            {
                OnRecordDateChanging(value);
                ReportPropertyChanging("RecordDate");
                _RecordDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RecordDate");
                OnRecordDateChanged();
            }
        }
        private global::System.DateTime _RecordDate;
        partial void OnRecordDateChanging(global::System.DateTime value);
        partial void OnRecordDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RowPointer
        {
            get
            {
                return _RowPointer;
            }
            set
            {
                OnRowPointerChanging(value);
                ReportPropertyChanging("RowPointer");
                _RowPointer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RowPointer");
                OnRowPointerChanged();
            }
        }
        private global::System.Guid _RowPointer;
        partial void OnRowPointerChanging(global::System.Guid value);
        partial void OnRowPointerChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EXACTUSModel", Name="ADMIN_CONCEPTO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ADMIN_CONCEPTO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ADMIN_CONCEPTO object.
        /// </summary>
        /// <param name="aDMINISTRADORA">Initial value of the ADMINISTRADORA property.</param>
        /// <param name="cONCEPTO">Initial value of the CONCEPTO property.</param>
        /// <param name="noteExistsFlag">Initial value of the NoteExistsFlag property.</param>
        /// <param name="recordDate">Initial value of the RecordDate property.</param>
        /// <param name="rowPointer">Initial value of the RowPointer property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="updatedBy">Initial value of the UpdatedBy property.</param>
        /// <param name="createDate">Initial value of the CreateDate property.</param>
        public static ADMIN_CONCEPTO CreateADMIN_CONCEPTO(global::System.String aDMINISTRADORA, global::System.String cONCEPTO, global::System.Byte noteExistsFlag, global::System.DateTime recordDate, global::System.Guid rowPointer, global::System.String createdBy, global::System.String updatedBy, global::System.DateTime createDate)
        {
            ADMIN_CONCEPTO aDMIN_CONCEPTO = new ADMIN_CONCEPTO();
            aDMIN_CONCEPTO.ADMINISTRADORA = aDMINISTRADORA;
            aDMIN_CONCEPTO.CONCEPTO = cONCEPTO;
            aDMIN_CONCEPTO.NoteExistsFlag = noteExistsFlag;
            aDMIN_CONCEPTO.RecordDate = recordDate;
            aDMIN_CONCEPTO.RowPointer = rowPointer;
            aDMIN_CONCEPTO.CreatedBy = createdBy;
            aDMIN_CONCEPTO.UpdatedBy = updatedBy;
            aDMIN_CONCEPTO.CreateDate = createDate;
            return aDMIN_CONCEPTO;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ADMINISTRADORA
        {
            get
            {
                return _ADMINISTRADORA;
            }
            set
            {
                if (_ADMINISTRADORA != value)
                {
                    OnADMINISTRADORAChanging(value);
                    ReportPropertyChanging("ADMINISTRADORA");
                    _ADMINISTRADORA = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ADMINISTRADORA");
                    OnADMINISTRADORAChanged();
                }
            }
        }
        private global::System.String _ADMINISTRADORA;
        partial void OnADMINISTRADORAChanging(global::System.String value);
        partial void OnADMINISTRADORAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CONCEPTO
        {
            get
            {
                return _CONCEPTO;
            }
            set
            {
                if (_CONCEPTO != value)
                {
                    OnCONCEPTOChanging(value);
                    ReportPropertyChanging("CONCEPTO");
                    _CONCEPTO = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CONCEPTO");
                    OnCONCEPTOChanged();
                }
            }
        }
        private global::System.String _CONCEPTO;
        partial void OnCONCEPTOChanging(global::System.String value);
        partial void OnCONCEPTOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte NoteExistsFlag
        {
            get
            {
                return _NoteExistsFlag;
            }
            set
            {
                if (_NoteExistsFlag != value)
                {
                    OnNoteExistsFlagChanging(value);
                    ReportPropertyChanging("NoteExistsFlag");
                    _NoteExistsFlag = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NoteExistsFlag");
                    OnNoteExistsFlagChanged();
                }
            }
        }
        private global::System.Byte _NoteExistsFlag;
        partial void OnNoteExistsFlagChanging(global::System.Byte value);
        partial void OnNoteExistsFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RecordDate
        {
            get
            {
                return _RecordDate;
            }
            set
            {
                if (_RecordDate != value)
                {
                    OnRecordDateChanging(value);
                    ReportPropertyChanging("RecordDate");
                    _RecordDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecordDate");
                    OnRecordDateChanged();
                }
            }
        }
        private global::System.DateTime _RecordDate;
        partial void OnRecordDateChanging(global::System.DateTime value);
        partial void OnRecordDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RowPointer
        {
            get
            {
                return _RowPointer;
            }
            set
            {
                if (_RowPointer != value)
                {
                    OnRowPointerChanging(value);
                    ReportPropertyChanging("RowPointer");
                    _RowPointer = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RowPointer");
                    OnRowPointerChanged();
                }
            }
        }
        private global::System.Guid _RowPointer;
        partial void OnRowPointerChanging(global::System.Guid value);
        partial void OnRowPointerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                if (_CreatedBy != value)
                {
                    OnCreatedByChanging(value);
                    ReportPropertyChanging("CreatedBy");
                    _CreatedBy = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CreatedBy");
                    OnCreatedByChanged();
                }
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                if (_UpdatedBy != value)
                {
                    OnUpdatedByChanging(value);
                    ReportPropertyChanging("UpdatedBy");
                    _UpdatedBy = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UpdatedBy");
                    OnUpdatedByChanged();
                }
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                if (_CreateDate != value)
                {
                    OnCreateDateChanging(value);
                    ReportPropertyChanging("CreateDate");
                    _CreateDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CreateDate");
                    OnCreateDateChanged();
                }
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();

        #endregion

    
    }

    #endregion

    
}
